Upgrade Skaffold version to v1.20.0
metro-digital/setup-tools-for-waas pull request #20
Opened 2021-02-25 10:13 UTC by navyatejaotturu-metronom

The github workflow generated for waas/v1alpha4 uses "skaffold build" command to build and push the container image to container registry where we are using "ignoreChanges" option under "tagPolicy" in Sakffold configuration file which needs v1.20.0 of Skaffold binary.

2021-02-25 13:29 UTC, blazej-budzynski requested changes
Could please update also 'install' test to the latest skaffold version

2021-02-26 09:22 UTC, navyatejaotturu-metronom commented
> Could please update also 'install' test to the latest skaffold version

After you mentioned this here, I had a look at the tests and was thinking if we really need them as we are already using the action and installing all the tools in the test workflow which is similar to the install tests we are doing.
https://github.com/metro-digital/setup-tools-for-waas/blob/2b19fbb5442066e28f1ce120173e72da9d22c413/.github/workflows/test.yml#L27-L29

I would prefer to remove these tests.

2021-02-26 09:33 UTC, blazej-budzynski commented
> I would prefer to remove these tests.

I would prefer to keep them both. Unit tests can be run locally within IDE and this is quite convenient for quickly checking the implementation. The 'test workflow' checks if action runs 'as a whole' (and it is low maintenance).

2021-02-26 09:54 UTC, PatrykBruder approved these changes
LGTM 👯‍♀️

2021-02-26 10:05 UTC, blazej-budzynski approved these changes

2021-02-26 10:05 UTC, merged